:hivemq-link: http://www.hivemq.com
:hivemq-plugin-docs-link: http://www.hivemq.com/docs/plugins/2.0.0/
:hivemq-plugin-docs-archetype-link: http://www.hivemq.com/docs/plugins/2.0.0/#maven-archetype-chapter
:hivemq-blog-tools: http://www.hivemq.com/overview-of-mqtt-client-tools/
:hivemq-callbacks-overview-link: http://www.hivemq.com/docs/plugins/2.0.0/#hivemqdocs_overview_of_all_callbacks
:github-low-level-callbacks: https://github.com/hivemq/hivemq-spi/tree/master/src/main/java/com/dcsquare/hivemq/spi/callback/lowlevel
:maven-documentation-profile-link: http://maven.apache.org/guides/introduction/introduction-to-profiles.html
:hivemq-support-forum: http://www.hivemq.com/support-forum/

== HiveMQ Persistent Shared Subscriptions Plugin

=== Purpose

This plugin will persist any message to a shared subscription topic if currently no clients are active/available for that shared subscription.
As soon as a new client connects to the shared subscription, it will receive all missed messages.

=== What you'll get

Currently all storage is in memory so it is NOT distributed !!

Based on the OnSubscribe, OnUnsubscribe and OnDisconnect the plugins keeps track of active clients for a shared subscription.
On OnPublishReceived the plugin will store a message to a shared subscription if no clients are active anymore.
As soon as a new client subscribes on an existing shared subscription, this client will receive all missed messages.

=== Trying the plugin

. Execute the +package+ goal from Maven with the profile _RunWithHiveMQ_ activated. (Need help?: Consult: {maven-documentation-profile-link}[The maven documentation])
. Now HiveMQ should be running *with* your plugin installed.
. Connect with a {hivemq-blog-tools}[MQTT client] of your choice and publish something. You should see some log output.


=== Issues

When testing this plugin in IDE (IntelliJ) to plugin does deliver the messages for an existing shared subscription
when a new shared subscription client connects when a breakpoint is added in the function PersistSharedSubscriptionMessageService.sendMessagesToClient
but the messages do not arrive at the client when no breakpoint is set.
